
theme: jekyll-theme-cayman
gems:
  - jekyll-octicons

title: Long-Read, long reach Bioinformatics Tutorials
description: 


# Staticman
staticman:
 allowedFields: ['name', 'address','comment']
 branch: gh-pages
 filename: "entry{@timestamp}"
 format: yml
 moderation: false
 path: "_data/comments"
 requiredFields: ['name', 'address', 'comment']
