
theme: jekyll-theme-cayman
gems:
  - jekyll-octicons

title: Long-Read, long reach Bioinformatics Tutorials
description: 

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
include:
  - QC.md

